services:
  - type: web
    name: gym-website
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
